import Head from 'next/head'
import type { AppProps } from 'next/app'

// styles
import "../styles/index.scss";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
        <Head>
          <title>do they exist?</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  )
}
